created delete method
pdx-cs-rust-web/knock-knock pull request #5
Opened 2024-04-18 12:13 UTC by NoodleSamaChan

hello!

fixes 4

please don't hesitate to let me know if there are any issues.
Cheers!

2024-04-18 22:18 UTC, BartMassey commented
Don't have the earlier PR: guessing you deleted it?

So force-push your whole branch, so that I can get all the commits there.

2024-04-18 23:03 UTC, irevoire requested changes
You should also define a new HTTP route on the frontend in this file that calls the method you just defined on the database: https://github.com/pdx-cs-rust-web/knock-knock/blob/main/src/api.rs

2024-04-18 23:03 UTC, irevoire commented on src/jokebase.rs
> +            Ok(())
```suggestion
            self.jokemap.remove(&given_id);
            self.write_jokes()?;
            Ok(())
```

After updating the jokemap, we should update the on-disk version of the database.
This way, if a crash occurs after the deletion, we’ll be able to restart the database without losing any operations.

2024-04-19 13:03 UTC, NoodleSamaChan commented
hello both!

Thanks very much for your feedback, I'm working on including everything!

@BartMassey terribly sorry I'm still quite new to this, this is actually my first PR, I didn't do any other prior to this one : )

@irevoire I've included the HTTP route following the example of utoipa with Axum: https://github.com/juhaku/utoipa/blob/master/examples/todo-axum/src/main.rs
I'm not getting any error messages so hopefully I did it properly.

Cheers!

2024-04-20 17:37 UTC, irevoire approved these changes
noice

2024-04-22 06:55 UTC, BartMassey commented
@NoodleSamaChan @irevoire I've pushed more changes to the API source, sadly. If you can rebase onto these I'll go ahead and merge this.

2024-04-22 13:36 UTC, NoodleSamaChan commented
@BartMassey okay it should be all good now! Thanks for your patience, don't hesitate to let me know if there are any questions : )

2024-04-22 16:26 UTC, merged

2024-04-22 16:27 UTC, BartMassey commented
Still needed some work, but I went ahead and merged anyhow. I'll rebase my fixes onto the result.

Thanks much for the contribution!